name: Deploy Python Server

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出仓库代码
      - name: Check out the repository
        uses: actions/checkout@v2

      # 2. 部署到远程服务器
      - name: Deploy to server
        uses: easingthemes/ssh-deploy@v2.1.1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          REMOTE_HOST: "home.mic.run"
          REMOTE_USER: "mic"
          TARGET: '/home/jujiubot'
          ARGS: "-avzr --delete"
          SOURCE: "./"
          EXCLUDE: "/venv/"
          SSH_OPTIONS: "-o StrictHostKeyChecking=no -p 44444"  # 指定自定义端口和其他 SSH 选项
        with:
          # 强制 Rsync 使用指定的端口
          rsh: "ssh -i /home/runner/.ssh/deploy_key -o StrictHostKeyChecking=no -p 44444"

      # 3. 重启远程服务器上的守护进程
      - name: Restart the service
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -p 44444 mic@home.mic.run << 'EOF'
          sudo systemctl restart your_service_name
          EOF
