name: Deploy JuJiuBot

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出仓库代码
      - name: Check out the repository
        uses: actions/checkout@v2

      # 2. 部署到远程服务器
      - name: Deploy to server
        uses: easingthemes/ssh-deploy@v2.1.1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}  # 服务器的域名，不带端口号
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: '/home/jujiubot'
          ARGS: "-avzr --delete" 
          SOURCE: "./"
          EXCLUDE: "/.idea/"
          SSH_OPTIONS: "-p 44444"  # 指定自定义端口号

      # 3. 重启远程服务器上的守护进程
      - name: Restart the service
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -p 44444 mic@home.mic.run << 'EOF'
          sudo systemctl restart jujiubot
          EOF
