name: Deploy Python Server

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出仓库代码
      - name: Check out the repository
        uses: actions/checkout@v2

      # 2. 安装Python环境（可选，如果需要执行Python相关的任务，比如运行测试等）
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # 3. 部署到远程服务器
      - name: Deploy to server
        uses: easingthemes/ssh-deploy@v2.1.1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          ARGS: "-avzr --delete" 
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: '/home/jujiubot'
          EXCLUDE: "/.idea/"

      # 4. 重启远程服务器上的守护进程
      - name: Restart the service
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.REMOTE_USER }}@${{ secrets.HOST }} << 'EOF'
          sudo systemctl restart jujiubot
          EOF
