name: Deploy JuJiuBot

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出仓库代码
      - name: Check out the repository
        uses: actions/checkout@v2

      # 2. 部署到远程服务器
      - name: Deploy to server
        uses: easingthemes/ssh-deploy@v2.1.1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}    # 将主机信息放入 GitHub Secrets
          REMOTE_USER: ${{ secrets.REMOTE_USER }}    # 将用户信息放入 GitHub Secrets
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}    # 将端口信息放入 GitHub Secrets
          TARGET: '/home/jujiubot'
          ARGS: "-avzr --delete"
          SOURCE: "./"
          EXCLUDE: "/venv/"

      # 3. 重启远程服务器上的守护进程
      - name: Restart the service
        run: |
          echo "${{ secrets.PRIVATE_KEY }}" | ssh -o StrictHostKeyChecking=no -i /dev/stdin -p ${{ secrets.REMOTE_PORT }} ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} << 'EOF'
          sudo systemctl restart Bot
          EOF
